#!/bin/bash
#
# Builds newsman.zip for uploading as a GitHub release.
# Store owners install the PrestaShop 9.x module by uploading this archive
# via PrestaShop Admin > Modules > Upload a module.
#
# Steps:
#   1. Copies the module directory to a temporary location as newsman/
#   2. Backs up vendor/index.php and vendor/.htaccess (PrestaShop security files)
#   3. Removes dot-directories (.git, etc.) and dot-files
#   4. Removes tools/ and tests/ directories
#   5. Deletes vendor/ and composer.lock, runs composer install --no-dev
#   6. Removes composer.lock generated by composer install
#   7. Restores vendor/index.php and vendor/.htaccess
#   8. Cleans non-runtime files from vendor packages
#   9. Creates the zip archive with newsman/ as root directory
#
# Usage:
#   ./build-release-zip.sh <module_dir> <php_binary> <composer_path> <output_zip>
#
# Example:
#   ./build-release-zip.sh /path/to/modules/newsman php8.2 /usr/local/bin/composer /tmp/newsman.zip

set -e

if [ $# -ne 4 ]; then
    echo "Usage: $0 <module_dir> <php_binary> <composer_path> <output_zip>"
    echo "  module_dir     — path to the Newsman module directory"
    echo "  php_binary     — PHP binary to use (e.g. php8.2)"
    echo "  composer_path  — path to the Composer binary (e.g. /usr/local/bin/composer)"
    echo "  output_zip     — output path for the .zip archive"
    exit 1
fi

MODULE_DIR="$(realpath "$1")"
PHP_BIN="$2"
COMPOSER_PATH="$3"
OUTPUT_ZIP="$4"

if [ ! -d "$MODULE_DIR" ]; then
    echo "Error: $MODULE_DIR does not exist."
    exit 1
fi

if [ ! -f "$MODULE_DIR/newsman.php" ]; then
    echo "Error: $MODULE_DIR/newsman.php not found. Is this the correct module directory?"
    exit 1
fi

if [ ! -f "$MODULE_DIR/composer.json" ]; then
    echo "Error: $MODULE_DIR/composer.json not found."
    exit 1
fi

# Resolve output path to absolute.
case "$OUTPUT_ZIP" in
    /*) ;;
    *) OUTPUT_ZIP="$(pwd)/$OUTPUT_ZIP" ;;
esac

echo "Module dir  : $MODULE_DIR"
echo "PHP binary  : $PHP_BIN"
echo "Composer    : $COMPOSER_PATH"
echo "Output      : $OUTPUT_ZIP"
echo ""

# Step 1: Copy module to a temp directory.
echo "=== Step 1: Copying module to temporary directory ==="
TEMP_DIR=$(mktemp -d)
trap 'rm -rf "$TEMP_DIR"' EXIT

cp -a "$MODULE_DIR" "$TEMP_DIR/newsman"
WORK_DIR="$TEMP_DIR/newsman"
echo "Copied to: $WORK_DIR"
echo ""

# Step 2: Back up vendor/index.php and vendor/.htaccess (before dot-file removal).
echo "=== Step 2: Backing up vendor security files ==="
BACKUP_DIR=$(mktemp -d)
if [ -f "$WORK_DIR/.htaccess" ]; then
    cp "$WORK_DIR/.htaccess" "$BACKUP_DIR/root-.htaccess"
    echo "Backed up: .htaccess"
fi
for file in vendor/index.php vendor/.htaccess; do
    if [ -f "$WORK_DIR/$file" ]; then
        cp "$WORK_DIR/$file" "$BACKUP_DIR/$(basename "$file")"
        echo "Backed up: $file"
    fi
done
echo ""

# Step 3: Remove dot-directories and dot-files.
echo "=== Step 3: Removing dot-directories and dot-files ==="
find "$WORK_DIR" -mindepth 1 -name '.*' | while read -r entry; do
    rm -rf "$entry"
    echo "Removed: $entry"
done
echo ""

# Step 4: Remove tools/ and tests/ directories.
echo "=== Step 4: Removing tools/ and tests/ directories ==="
for dir in tools tests; do
    if [ -d "$WORK_DIR/$dir" ]; then
        rm -rf "$WORK_DIR/$dir"
        echo "Removed: $WORK_DIR/$dir"
    fi
done
echo ""

# Step 5: Delete vendor/ and composer.lock, run composer install --no-dev.
echo "=== Step 5: Cleaning vendor and running composer install --no-dev ==="
if [ -d "$WORK_DIR/vendor" ]; then
    rm -rf "$WORK_DIR/vendor"
    echo "Deleted: $WORK_DIR/vendor"
fi
if [ -f "$WORK_DIR/composer.lock" ]; then
    rm "$WORK_DIR/composer.lock"
    echo "Deleted: $WORK_DIR/composer.lock"
fi

cd "$WORK_DIR"
"$PHP_BIN" "$COMPOSER_PATH" install --no-dev -vvv
echo ""

# Step 6: Remove composer.lock generated by composer install.
echo "=== Step 6: Removing composer.lock ==="
if [ -f "$WORK_DIR/composer.lock" ]; then
    rm "$WORK_DIR/composer.lock"
    echo "Deleted: $WORK_DIR/composer.lock"
fi
echo ""

# Step 7: Restore vendor/index.php and vendor/.htaccess.
echo "=== Step 7: Restoring vendor security files ==="
if [ -f "$BACKUP_DIR/root-.htaccess" ]; then
    cp "$BACKUP_DIR/root-.htaccess" "$WORK_DIR/.htaccess"
    echo "Restored: .htaccess"
fi
for file in index.php .htaccess; do
    if [ -f "$BACKUP_DIR/$file" ]; then
        cp "$BACKUP_DIR/$file" "$WORK_DIR/vendor/$file"
        echo "Restored: vendor/$file"
    fi
done
rm -rf "$BACKUP_DIR"
echo ""

# Step 8: Clean non-runtime files from vendor packages.
echo "=== Step 8: Cleaning non-runtime files from vendor ==="
VENDOR_DIR="$WORK_DIR/vendor"

# Remove known non-runtime directories.
for dir in tests test examples example libs wiki doc docs .github .settings; do
    find "$VENDOR_DIR" -mindepth 2 -maxdepth 3 -type d -name "$dir" | while read -r d; do
        rm -rf "$d"
        echo "Removed: $d"
    done
done

# Remove non-runtime files from package roots.
for pattern in phpunit.xml phpunit.xml.dist phpunit.xml.dist.bak .travis.yml .gitignore .gitattributes .gitmodules .buildpath .project .eclipse-PHP-formatter.xml runtest.sh README.md CHANGELOG.md CONTRIBUTING.md; do
    find "$VENDOR_DIR" -mindepth 2 -maxdepth 3 -type f -name "$pattern" | while read -r f; do
        rm "$f"
        echo "Removed: $f"
    done
done
echo ""

# Step 9: Create the zip archive.
echo "=== Step 9: Creating zip archive ==="
[ -f "$OUTPUT_ZIP" ] && rm "$OUTPUT_ZIP"

cd "$TEMP_DIR"
zip -r "$OUTPUT_ZIP" newsman/

echo ""
echo "=== Done ==="
echo "Archive created: $OUTPUT_ZIP"
echo "Size: $(du -h "$OUTPUT_ZIP" | cut -f1)"
